using System;
using System.Linq;
using System.Text;
using Uoc.Chart;
using Uoc.Chart.Notes;
using Uoc.Chart.Notes.Definition;
using Uoc.Chart.Property;

namespace Uoc.Parse
{
    /// <summary>
    /// UOC文字列の構築を行う静的クラス
    /// </summary>
    public static class UocBuilder
    {

        public static UocString Build(string editorName, ChartPropertyGroup chartPropertyGroup, NoteDefCollection noteDefCollection, NoteGroupDefCollection noteGroupDefCollection, NoteProfileCollection noteProfileCollection)
        {
            if (string.IsNullOrWhiteSpace(editorName)) throw new ArgumentException(nameof(editorName));
            if (chartPropertyGroup == null) throw new ArgumentNullException(nameof(chartPropertyGroup));
            if (noteDefCollection == null) throw new ArgumentNullException(nameof(noteDefCollection));
            if (noteGroupDefCollection == null) throw new ArgumentNullException(nameof(noteGroupDefCollection));
            if (noteProfileCollection == null) throw new ArgumentNullException(nameof(noteProfileCollection));

            var header = BuildHeader(editorName);
            var chartPropertiesSection = BuildChartPropertiesSectionString(chartPropertyGroup);
            var notesDefsSection = BuildNotesDefsSectionString(noteDefCollection, noteGroupDefCollection);
            var chartSction = BuildChartSectionString(noteDefCollection, noteProfileCollection);
            return new UocString(header + chartPropertiesSection + notesDefsSection + chartSction);
        }

        private static string BuildHeader(string editorName)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine($"This is the UOC file generated by \"{editorName}\".");
            stringBuilder.AppendLine();

            return stringBuilder.ToString();
        }

        private static string BuildChartPropertiesSectionString(ChartPropertyGroup chartPropertyGroup)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine($"@ PROPERTIES");
            stringBuilder.AppendLine($"# GameID : \"{chartPropertyGroup.GetGameId()}\"");
            stringBuilder.AppendLine($"# TicksPerBeat : \"{chartPropertyGroup.GetTpb().Value}\"");
            for (int i = 0; i < chartPropertyGroup.Count; i++)
            {
                var property = chartPropertyGroup[i];
                if (property.Key.Value == "GameID" || property.Key.Value == "TicksPerBeat" || property.Key.Value == "Title") continue;
                stringBuilder.AppendLine($"# {property.Key.Value} : \"{property.Value.AsString()}\"");
            }
            stringBuilder.AppendLine();

            return stringBuilder.ToString();
        }

        private static string BuildNotesDefsSectionString(NoteDefCollection noteDefCollection, NoteGroupDefCollection noteGroupDefCollection)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine($"@ NOTESDEFS");
            var noteDefs = noteDefCollection.NoteDefs;
            for (int i = 0; i < noteDefs.Count; i++)
            {
                var noteDef = noteDefs[i];
                var line = $"# NOTEDEF \"{noteDef.NoteId.Value}\", ";
                for (int j = 0; j < noteDef.PropertyNames.Count; j++)
                {
                    line += $"\"{noteDef.PropertyNames[j]}\", ";
                }
                line = line[0..^2]; // 末尾のコンマ削除
                stringBuilder.AppendLine(line);
            }
            var noteGroupDefs = noteGroupDefCollection.NoteGroupDefs;
            for (int i = 0; i < noteGroupDefs.Count; i++)
            {
                var noteGroupDef = noteGroupDefs[i];
                var line = $"# NOTEGROUPDEF \"{noteGroupDef.NoteGroupId.Value}\", ";
                for (int j = 0; j < noteGroupDef.BelongsNoteIds.Count; j++)
                {
                    line += $"\"{noteGroupDef.BelongsNoteIds[j].Value}\", ";
                }
                line = line[0..^2]; // 末尾のコンマ削除
                stringBuilder.AppendLine(line);
            }
            stringBuilder.AppendLine();

            return stringBuilder.ToString();
        }

        private static string BuildChartSectionString(NoteDefCollection noteDefCollection, NoteProfileCollection noteProfileCollection)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine($"@ CHART");
            var noteProfiles = noteProfileCollection.NoteProfiles;

            // レイヤーごとに処理
            for (int i = 0; i < Layer.MaxLayerValue; i++)
            {
                var notesInLayer = noteProfiles.Where(x => x.Layer.Value == i).OrderBy(x => x.Position.MeasureIndex.Value).ThenBy(x => x.Position.Position01).ToList();
                if (notesInLayer.Count == 0) continue;
                stringBuilder.AppendLine($"# LAYER : {i}");
                foreach (var note in notesInLayer)
                {
                    // TODO: MEASUREBSを実装する
                    if (note.Position.MeasureIndex.Value > 999) throw new Exception("小節番号を999より大きくすることはできません。");

                    var line = $"# {Base36.Encode(note.Position.MeasureIndex.Value).ToString().PadLeft(3, '0')}";
                    line += $"{Base36.Encode(noteDefCollection.GetNoteDefIndexById(note.NoteDef.NoteId).Value).PadLeft(2, '0')}";
                    line += $"{(!note.Channel.IsEmpty ? Base36.Encode(note.Channel.Value).ToString().PadLeft(2, '0') : "")} : ";
                    for (int j = 0; j < note.Position.SectionCount; j++)
                    {
                        line += j == note.Position.ActiveIndex ? "1" : "0";
                    }
                    line += $", ";
                    for (int j = 0; j < note.PropertyGroup.Count; j++)
                    {
                        line += $"{note.PropertyGroup[j].Value.AsString()}, ";
                    }
                    line = line[0..^2]; // 末尾のコンマ削除
                    stringBuilder.AppendLine(line);
                }
            }

            return stringBuilder.ToString();
        }
    }
}
